### ISSUE TITLE
wbemprox.dll expected locations are incorrect

### ISSUE THREAD

**Issue by hxnoyd** [wietze/HijackLibs#10]
File Path: C:\Windows\system32\wbem\wbemprox.dll
ExpectedLocations:
- '%SYSTEM32%\wbem'
- '%SYSWOW64%\wbem'

Update: The same issue happens with fastprox.dll and wbemsvc.dll.

**Comment by JoernHe** [comment]
same issue here with "fastprox.dll"

**Comment by wietze** [comment]
Thanks both @hxnoyd and @JoernHe for opening an issue for this, this is now fixed.
