### ISSUE TITLE
duplicate path specification (ciscosparklauncher.dll)

### ISSUE THREAD

**Issue by twistingjackomo** [wietze/HijackLibs#25]
%LOCALAPPDATA%\AppData\Local\CiscoSparkLauncher

https://hijacklibs.net/entries/3rd_party/cisco/ciscosparklauncher.html

"%LOCALAPPDATA%" stands for "\AppData\Local\"

**Comment by wietze** [comment]
Good spot, fixed in 81a4737ee8b34e28f1fb064f972ad4116798d1ed.

Thanks!
