### ISSUE TITLE
Add PE Header Information

### ISSUE THREAD

**Issue by Cyb3r-Monk** [wietze/HijackLibs#29]
Since it's is easy to rename the vulnerable executable, it would be great to add PE header information to the specification so that detections can be written for the original filename info.

**Comment by wietze** [comment]
That's right, for that reason hunting for the DLLs is preferred. Nevertheless, you're right, you could hunt for the executables as well, based on other properties than filename/location. Would  #13 meet your use case?

**Comment by Cyb3r-Monk** [comment]
Just hunting for the DLL(based on its expected location) created lots of false positives in my case. Looks like https://github.com/wietze/HijackLibs/pull/13 meets my use case.

**Comment by mgreen27** [comment]
Just adding a +1: VersionInformation + Signiture details to reduce FPs.

Looking at some VQL automation. For example, hunt MFT for dllname > check path > check VersionInfoirmation > check signiture would be the methodology.

**Comment by wietze** [comment]
Supported via #31 and #18; closing this issue for now. Thanks for the suggestions.
