### ISSUE TITLE
feature request: include DLLs injectable using environment variables

### ISSUE THREAD

**Issue by johnmccash** [wietze/HijackLibs#40]
Include binaries that are only injectable when certain environment variables are set, per this article: https://www.wietzebeukema.nl/blog/save-the-environment-variables
(hopefully you haven't already done this, or I'll be embarrassed)

**Comment by wietze** [comment]
They should all be included, take for example [propsys.dll](https://hijacklibs.net/entries/microsoft/built-in/propsys.html) :)

**Comment by johnmccash** [comment]
OMG... You're the same guy as the author of that post. I'm just gonna go off and die now... My bad.
